name: 🐞 Bug report
description: Report broken functionality
title: "[BUG] "
labels: [bug]

body:
- type: markdown
  attributes:
    value: |
      📋 **Guidelines:**

      - Search through [existing issues](https://github.com/BennyExtreme/yet-another-factory-planner/issues?q=is%3Aissue+label%3Abug) first to ensure that this bug has not been reported before.
      - Write a descriptive title for your issue. Avoid generic or vague titles such as "Something's not working" or "A couple of problems".
      - Keep your issue focused on one single problem. If you have multiple bug reports, please create separate issues for each of them.
      - Provide as much context as possible in the details section. Include screenshots, screen recordings, links, references, or anything else you may consider relevant.

- type: textarea
  attributes:
    label: Where
    description: |
      In which page did you find the problem?
      If the problem is not in a specific page or you don’t know, leave this field blank.
    placeholder: https://satisfactory.bennyextreme.tk/
  validations:
    required: false

- type: textarea
  attributes:
    label: Details
    description: Clear and thorough explanation of the bug.
    placeholder: I was doing X expecting Y to happen, but Z happened instead.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Minimum steps required to reproduce the bug.
    placeholder: |
      - Step 1
      - Step 2
      - Step 3
  validations:
    required: true
